import type { Metadata } from "next";
import { getUserFromToken } from "@/lib/auth";
import { redirect } from "@/i18n/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const user = await getUserFromToken();
  console.log({ user });
  return <>{user ? children : redirect({ href: "", locale })}</>;
}
