import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import Providers from "../providers";
import { getUserFromToken } from "@/lib/auth";
import { redirect } from "next/navigation";
import { ThemeProvider } from "@/components/theme-provider"

import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const user = await getUserFromToken();
  console.log({user})
  return (
    <Providers>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {
              user
              ?children
              :redirect('/login') // TODO: use next-intel 
            }
              <Toaster position="top-center" />
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}

